a = 12
b = 34
print(a + b)
print("branch test 1")
print("branch test 2")
print(a - b)
print("branch test 3")
print(a * b)
print("branch test 4")
print(a / b)
print("branch test 5")
print(a % b)
print("branch test 6")
print(a ** b)
print("branch test 7")

print(a // b)
print("branch test 8")
print(a % b)